### ISSUE TITLE
Error in packageApplication

### ISSUE THREAD

**Issue by elgca** [raquo/laminar-full-stack-demo#6]
I encountered an issue while trying to create a fat jar using `sbt packageApplication`

- OS  Windows 11.
- Java Version 21

First, the npm command was not being found, even though npm is already in my system environment and I can invoke npm commands from any command line. I resolved this by replacing `npm` with `cmd /c npm` in the `build.sbt` file. I tried the same code in the scala cli and got the same result, 'npm not found'. I'm wondering why? 

Now, I'm stuck with a new problem and unable to solve it. Below is my error log:
```
[info] welcome to sbt 1.10.0 (Eclipse Adoptium Java 21.0.3)
[info] loading settings for project root from build.sbt,plugins.sbt,idea64087.sbt ...
[info] loading project definition from C:\Users\Administrator\IdeaProjects\laminar-full-stack-demo\project
[info] loading settings for project root from build.sbt ...
[info] set current project to Laminar Demo (in build file:/C:/Users/Administrator/IdeaProjects/laminar-full-stack-demo/)
[info] Defining Global / ideaPort
[info] The new value will be used by Compile / compile, Test / compile and 7 others.
[info]  Run `last` for details.
[info] Reapplying settings...
[info] set current project to Laminar Demo (in build file:/C:/Users/Administrator/IdeaProjects/laminar-full-stack-demo/)
[IJ]packageApplication
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

added 267 packages in 16s

29 packages are looking for funding
  run `npm fund` for details

> laminar-demo@0.1.0 build
> vite build

vite v5.2.10 building for production...
sbt.internal.ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load7988701669316599629_lock, error 5
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:357)
        at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:296)
        at sbt.xMain$.getSocketOrExit(Main.scala:152)
        at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:78)
        at sbt.xMain$.bootServerSocket$1(Main.scala:78)
        at sbt.xMain$.withStreams$1(Main.scala:86)
        at sbt.xMain$.run(Main.scala:123)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
        at sbt.xMain.run(Main.scala:47)
        at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
        at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
        at xsbt.boot.Launch$.run(Launch.scala:149)
        at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
        at xsbt.boot.Launch$.launch(Launch.scala:159)
        at xsbt.boot.Launch$.apply(Launch.scala:44)
        at xsbt.boot.Launch$.apply(Launch.scala:21)
        at xsbt.boot.Boot$.runImpl(Boot.scala:78)
        at xsbt.boot.Boot$.run(Boot.scala:73)
        at xsbt.boot.Boot$.main(Boot.scala:21)
        at xsbt.boot.Boot.main(Boot.scala)
Caused by: java.io.IOException: Could not create lock for \\.\pipe\sbt-load7988701669316599629_lock, error 5
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:129)
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:48)
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:351)
        ... 21 more
sbt thinks that server is already booting because of this exception:
?[31mx?[39m Build failed in 1.13s
?[31merror during build:
Error: ?[31m[scalajs:sbt-scalajs-plugin] sbt invocation for Scala.js compilation failed with exit code 1.?[31m
    at ChildProcess.<anonymous> (file:///C:/Users/Administrator/IdeaProjects/laminar-full-stack-demo/client/node_modules/@scala-js/vite-plugin-scalajs/dist/index.js:24:24)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)?[39m
✓ 0 modules transformed.
```

**Comment by raquo** [comment]
Hm I'm not familiar with windows but can you please try to change `npm` to `npm.bat` (without /c) and see if that works? I've seen that used before in Scala projects, wasn't sure why.

Regarding the sbt exception, i haven't encountered that myself, but it seems related to this: https://github.com/sbt/sbt/issues/6777 – there's a suggested workaround there.

**Comment by elgca** [comment]
Actually, the `/c` flag must be included. I experimented with Scala REPL without the `/c` flag, and there's no difference in running npm or npm.bat on Windows.
```
scala> import scala.sys.process.Process

scala> import java.io.File

scala> val a = Process("cmd npm list", new File("client")).!
Microsoft Windows [Version 10.0.22631.3593]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Administrator\IdeaProjects\laminar-full-stack-demo\client> // This locking in REPL, making it unoperable, so I have to force quit.
```
This is the case when I used '/c':
```
scala>
       val a = Process("cmd /c npm ci", new File("client")).!
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

added 267 packages in 11s

29 packages are looking for funding
  run `npm fund` for details
val a: Int = 0

scala> val a = Process("cmd /c npm run build", new File("client")).!

> laminar-demo@0.1.0 build
> vite build

vite v5.2.10 building for production...
[info] welcome to sbt 1.10.0 (Eclipse Adoptium Java 21.0.3)
[info] loading settings for project root from build.sbt,plugins.sbt ...
[info] loading project definition from C:\Users\Administrator\IdeaProjects\laminar-full-stack-demo\project
[info] loading settings for project root from build.sbt ...
[info] set current project to Laminar Demo (in build file:/C:/Users/Administrator/IdeaProjects/laminar-full-stack-demo/)
[info] compiling 1 Scala source to C:\Users\Administrator\IdeaProjects\laminar-full-stack-demo\client\target\scala-3.4.1\classes ...
[info] done compiling
[info] Full optimizing C:\Users\Administrator\IdeaProjects\laminar-full-stack-demo\client\target\scala-3.4.1\client-opt
C:\Users\Administrator\IdeaProjects\laminar-full-stack-demo\client\target\scala-3.4.1\client-opt
transforming...
node_modules/antd/es/index.js (1:0): Module level directives cause errors when bundled, "use client" in "nod
...

...
dist/assets/ru_UA-Dl_FCCBg.js       86.10 kB │ gzip:  12.11 kB │ map:     0.10 kB
dist/assets/ru-BpX8gQg0.js          86.14 kB │ gzip:  12.12 kB │ map:     0.10 kB
dist/assets/ar-5E0AXR3y.js         109.84 kB │ gzip:  14.49 kB │ map:     0.10 kB
dist/assets/ar_EG-5E0AXR3y.js      109.84 kB │ gzip:  14.50 kB │ map:     0.10 kB
dist/assets/ar_SA-BbvsdfQp.js      109.91 kB │ gzip:  14.65 kB │ map:     0.10 kB
dist/assets/index-DQr4gF5s.js    2,254.80 kB │ gzip: 577.11 kB │ map: 5,922.01 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 36.13s
val a: Int = 0

scala> //Here I successfully completed the call and can continue using Scala REPL. Nice, it works!!!
```
Then I modified `build.sbt`.
```
Process(s"cmd /c ci", cwd = (client / baseDirectory).value).!
~~
Process(s"cmd /c run build", cwd = (client / baseDirectory).value).!
```
back project dir, run `sbt packageApplication `, i got errr:
```
Caused by: java.io.IOException: Could not create lock for \\.\pipe\sbt-load7988701669316599629_lock, error 5
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:129)
        at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:48)
        at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:351)
        ... 21 more
```
From the logs, it seems sbt uses Process to call `npm run build`. However, due to the vite plugin `@scala-js/vite-plugin-scalajs`,
 it starts another `sbt` session, which requires a lock. Is there a way to make npm package not require a lock or avoid starting sbt?

Currently, I removed npm command from `build.sbt` and completed my first package manually.

**Comment by elgca** [comment]
https://github.com/sbt/sbt/issues/6777#issuecomment-1613316167

need env:
```
SBT_SERVER_FORCESTART=1
SBT_TERMINAL_PROPS="80,20,false,false,false"
```

it works!!!!

thanks!

**Comment by raquo** [comment]
Ok, good that it works, thanks for confirming.

Unfortunately I don't understand in which cases these env are needed, and why are they only needed on Windows, but not e.g. on MacOS. If anyone reading this has any insight about that, please share, it would be good to update this project's docs to include that info.

As for the npm command, I asked in scala-js discord, and you're right, it looks like `cmd /c npm` is the most compatible way to call npm on Windows. I guess I'll need to update build.sbt with this Windows-specific command.
